/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_francisicosantos;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author Francisco Santos
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_AgregarJugador = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tf_nombreJ = new javax.swing.JTextField();
        tf_precio = new javax.swing.JTextField();
        cb_pos = new javax.swing.JComboBox<>();
        tf_habilidad = new javax.swing.JTextField();
        tf_tecnica = new javax.swing.JTextField();
        tf_resistencia = new javax.swing.JTextField();
        bt_AgregarJugadores = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jd_AgregarEquipo = new javax.swing.JDialog();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tf_nombreE = new javax.swing.JTextField();
        tf_presupuesto = new javax.swing.JTextField();
        tf_copas = new javax.swing.JTextField();
        tf_estadio = new javax.swing.JTextField();
        bt_AgregarEquipo = new javax.swing.JButton();
        jd_ListarJugadores = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_Jugadores = new javax.swing.JList<>();
        jLabel22 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        bt_jugadores = new javax.swing.JButton();
        jd_ListarEquipos = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_equipos = new javax.swing.JList<>();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jd_ListarLiga = new javax.swing.JDialog();
        jd_ModificarEquipo = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        tf_nombreE1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tf_presupuesto1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        tf_copas1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        tf_estadio1 = new javax.swing.JTextField();
        bt_modEquipos = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jd_ModificarJugador = new javax.swing.JDialog();
        jLabel27 = new javax.swing.JLabel();
        tf_nombreJ1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        tf_precio1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        cb_pos1 = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        tf_habilidad1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        tf_tecnica1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        tf_resistencia1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jd_ComprarJugador = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_CompraE = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_CompraJ = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        pop_jugadores = new javax.swing.JPopupMenu();
        pp_propiedades = new javax.swing.JMenuItem();
        pp_SacarJugador = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel9.setText("Nombre");

        jLabel10.setText("Precio");

        jLabel11.setText("Poscicion");

        jLabel12.setText("Habilidad");

        jLabel13.setText("Tecnica");

        jLabel14.setText("Resistencia");

        cb_pos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atacante", "MedioCampista", "Defensa", "Portero", " " }));

        bt_AgregarJugadores.setText("Agregar");
        bt_AgregarJugadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_AgregarJugadoresMouseClicked(evt);
            }
        });

        jLabel15.setText("%");

        jLabel16.setText("%");

        jLabel17.setText("%");

        javax.swing.GroupLayout jd_AgregarJugadorLayout = new javax.swing.GroupLayout(jd_AgregarJugador.getContentPane());
        jd_AgregarJugador.getContentPane().setLayout(jd_AgregarJugadorLayout);
        jd_AgregarJugadorLayout.setHorizontalGroup(
            jd_AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_AgregarJugadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(86, 86, 86)
                .addGroup(jd_AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_nombreJ)
                    .addComponent(tf_precio)
                    .addComponent(cb_pos, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_habilidad, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(tf_tecnica)
                    .addComponent(tf_resistencia))
                .addGroup(jd_AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_AgregarJugadorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(bt_AgregarJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(jd_AgregarJugadorLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jd_AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jd_AgregarJugadorLayout.setVerticalGroup(
            jd_AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AgregarJugadorLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jd_AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_nombreJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jd_AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jd_AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cb_pos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jd_AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_habilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(34, 34, 34)
                .addGroup(jd_AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_tecnica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(32, 32, 32)
                .addGroup(jd_AgregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_resistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addComponent(bt_AgregarJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jLabel18.setText("Nombre del Equipo");

        jLabel19.setText("Presupuesto");

        jLabel20.setText("Copas");

        jLabel21.setText("Nombre del Estadio");

        bt_AgregarEquipo.setText("Agregar Equipo");
        bt_AgregarEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_AgregarEquipoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_AgregarEquipoLayout = new javax.swing.GroupLayout(jd_AgregarEquipo.getContentPane());
        jd_AgregarEquipo.getContentPane().setLayout(jd_AgregarEquipoLayout);
        jd_AgregarEquipoLayout.setHorizontalGroup(
            jd_AgregarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AgregarEquipoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_AgregarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(69, 69, 69)
                .addGroup(jd_AgregarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_nombreE)
                    .addComponent(tf_presupuesto)
                    .addComponent(tf_copas)
                    .addComponent(tf_estadio, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                .addContainerGap(178, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_AgregarEquipoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_AgregarEquipo)
                .addGap(65, 65, 65))
        );
        jd_AgregarEquipoLayout.setVerticalGroup(
            jd_AgregarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AgregarEquipoLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(jd_AgregarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tf_nombreE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jd_AgregarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tf_presupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jd_AgregarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tf_copas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jd_AgregarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tf_estadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(bt_AgregarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        jl_Jugadores.setModel(new DefaultListModel());
        jl_Jugadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_JugadoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jl_Jugadores);

        jLabel22.setText("Lista de Jugadores");

        jButton1.setText("Modificar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        bt_jugadores.setText("Eliminar");
        bt_jugadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_jugadoresMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_ListarJugadoresLayout = new javax.swing.GroupLayout(jd_ListarJugadores.getContentPane());
        jd_ListarJugadores.getContentPane().setLayout(jd_ListarJugadoresLayout);
        jd_ListarJugadoresLayout.setHorizontalGroup(
            jd_ListarJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ListarJugadoresLayout.createSequentialGroup()
                .addGroup(jd_ListarJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ListarJugadoresLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jd_ListarJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_ListarJugadoresLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jButton1)
                        .addGap(103, 103, 103)
                        .addComponent(bt_jugadores)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jd_ListarJugadoresLayout.setVerticalGroup(
            jd_ListarJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ListarJugadoresLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel22)
                .addGap(57, 57, 57)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jd_ListarJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(bt_jugadores))
                .addGap(25, 25, 25))
        );

        jLabel7.setText("Lista de Equipos");

        jl_equipos.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl_equipos);

        jButton5.setText("Modificar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setText("Eliminar");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_ListarEquiposLayout = new javax.swing.GroupLayout(jd_ListarEquipos.getContentPane());
        jd_ListarEquipos.getContentPane().setLayout(jd_ListarEquiposLayout);
        jd_ListarEquiposLayout.setHorizontalGroup(
            jd_ListarEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ListarEquiposLayout.createSequentialGroup()
                .addGroup(jd_ListarEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ListarEquiposLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jd_ListarEquiposLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jd_ListarEquiposLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(121, 121, 121))
        );
        jd_ListarEquiposLayout.setVerticalGroup(
            jd_ListarEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ListarEquiposLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel7)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jd_ListarEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_ListarLigaLayout = new javax.swing.GroupLayout(jd_ListarLiga.getContentPane());
        jd_ListarLiga.getContentPane().setLayout(jd_ListarLigaLayout);
        jd_ListarLigaLayout.setHorizontalGroup(
            jd_ListarLigaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_ListarLigaLayout.setVerticalGroup(
            jd_ListarLigaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel23.setText("Nombre del Equipo");

        jLabel24.setText("Presupuesto");

        jLabel25.setText("Copas");

        jLabel26.setText("Nombre del Estadio");

        bt_modEquipos.setText("Modificar");
        bt_modEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_modEquiposMouseClicked(evt);
            }
        });

        jButton7.setText("Cargar");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_ModificarEquipoLayout = new javax.swing.GroupLayout(jd_ModificarEquipo.getContentPane());
        jd_ModificarEquipo.getContentPane().setLayout(jd_ModificarEquipoLayout);
        jd_ModificarEquipoLayout.setHorizontalGroup(
            jd_ModificarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ModificarEquipoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_modEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(jd_ModificarEquipoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_ModificarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addGap(69, 69, 69)
                .addGroup(jd_ModificarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_nombreE1)
                    .addComponent(tf_presupuesto1)
                    .addComponent(tf_copas1)
                    .addComponent(tf_estadio1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(21, 21, 21))
        );
        jd_ModificarEquipoLayout.setVerticalGroup(
            jd_ModificarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ModificarEquipoLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(jd_ModificarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tf_nombreE1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addGap(58, 58, 58)
                .addGroup(jd_ModificarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(tf_presupuesto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jd_ModificarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(tf_copas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jd_ModificarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(tf_estadio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(bt_modEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jLabel27.setText("Nombre");

        jLabel28.setText("Precio");

        jLabel29.setText("Poscicion");

        cb_pos1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atacante", "MedioCampista", "Defensa", "Portero", " " }));

        jLabel30.setText("Habilidad");

        jLabel31.setText("Tecnica");

        jLabel32.setText("Resistencia");

        jLabel33.setText("%");

        jLabel34.setText("%");

        jLabel35.setText("%");

        jButton3.setText("Cargar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("Modificar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_ModificarJugadorLayout = new javax.swing.GroupLayout(jd_ModificarJugador.getContentPane());
        jd_ModificarJugador.getContentPane().setLayout(jd_ModificarJugadorLayout);
        jd_ModificarJugadorLayout.setHorizontalGroup(
            jd_ModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ModificarJugadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_ModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32))
                .addGap(86, 86, 86)
                .addGroup(jd_ModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_nombreJ1)
                    .addComponent(tf_precio1)
                    .addComponent(cb_pos1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_habilidad1)
                    .addComponent(tf_tecnica1)
                    .addComponent(tf_resistencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jd_ModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ModificarJugadorLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jd_ModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(jLabel33)
                            .addComponent(jLabel35))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ModificarJugadorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(45, 45, 45))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ModificarJugadorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(58, 58, 58))
        );
        jd_ModificarJugadorLayout.setVerticalGroup(
            jd_ModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ModificarJugadorLayout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addGroup(jd_ModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(tf_nombreJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(39, 39, 39)
                .addGroup(jd_ModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(tf_precio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jd_ModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(cb_pos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jd_ModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(tf_habilidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addGap(34, 34, 34)
                .addGroup(jd_ModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(tf_tecnica1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addGap(32, 32, 32)
                .addGroup(jd_ModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(tf_resistencia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(49, 49, 49))
        );

        jl_CompraE.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jl_CompraE);

        jl_CompraJ.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(jl_CompraJ);

        jButton2.setText("Comprar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_ComprarJugadorLayout = new javax.swing.GroupLayout(jd_ComprarJugador.getContentPane());
        jd_ComprarJugador.getContentPane().setLayout(jd_ComprarJugadorLayout);
        jd_ComprarJugadorLayout.setHorizontalGroup(
            jd_ComprarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ComprarJugadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(jd_ComprarJugadorLayout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_ComprarJugadorLayout.setVerticalGroup(
            jd_ComprarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ComprarJugadorLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(jd_ComprarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addComponent(jButton2)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        pp_propiedades.setText("Propiedades");
        pp_propiedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pp_propiedadesActionPerformed(evt);
            }
        });
        pop_jugadores.add(pp_propiedades);

        pp_SacarJugador.setText("Sacar Jugador");
        pop_jugadores.add(pp_SacarJugador);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar Jugador");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 96, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 0));
        jLabel2.setText("Agregar Equipo");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 159, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 0));
        jLabel3.setText("Listar Jugadores");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 241, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 0));
        jLabel4.setText("Listar Equipos");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 314, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 0));
        jLabel5.setText("Listar Liga");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 382, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 255, 0));
        jLabel8.setText("Comprar Jugador");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab5_francisicosantos/foot2.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        jd_AgregarJugador.pack();
        jd_AgregarJugador.setModal(true);
        jd_AgregarJugador.setVisible(true);
        jd_AgregarJugador.setLocationRelativeTo(null);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        jd_AgregarEquipo.pack();
        jd_AgregarEquipo.setModal(true);
        jd_AgregarEquipo.setVisible(true);
        jd_AgregarEquipo.setLocationRelativeTo(null);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        jd_ListarJugadores.pack();
        jd_ListarJugadores.setModal(true);
        jd_ListarJugadores.setVisible(true);
        jd_ListarJugadores.setLocationRelativeTo(null);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        jd_ListarEquipos.pack();
        jd_ListarEquipos.setModal(true);
        jd_ListarEquipos.setVisible(true);
        jd_ListarEquipos.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        jd_ListarLiga.pack();
        jd_ListarLiga.setModal(true);
        jd_ListarLiga.setVisible(true);
        jd_ListarLiga.setLocationRelativeTo(null);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void bt_AgregarJugadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_AgregarJugadoresMouseClicked
        Jugador j = new Jugador(tf_nombreJ.getText(), Integer.parseInt(tf_precio.getText()), cb_pos.getSelectedItem().toString(), true, tf_habilidad.getText()+"%", tf_tecnica.getText()+"%", tf_resistencia.getText()+"%");
        jugadores.add(j);
        DefaultListModel modelo = (DefaultListModel)jl_Jugadores.getModel();
        modelo.addElement(j);
        jl_Jugadores.setModel(modelo);
        jl_CompraJ.setModel(modelo);
        //
        JOptionPane.showMessageDialog(null, "El jugador se agrego con exito");
        //
        tf_nombreJ.setText("");
        tf_precio.setText("");
        cb_pos.setSelectedIndex(0);
        tf_habilidad.setText("");
        tf_tecnica.setText("");
        tf_resistencia.setText("");
    }//GEN-LAST:event_bt_AgregarJugadoresMouseClicked

    private void bt_AgregarEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_AgregarEquipoMouseClicked
        Equipo e = new Equipo(tf_nombreE.getText(), Integer.parseInt(tf_presupuesto.getText()), Integer.parseInt(tf_copas.getText()), tf_estadio.getText());
        equipos.add(e);
        DefaultListModel modelo1 = (DefaultListModel)jl_equipos.getModel();
        modelo1.addElement(e);
        jl_equipos.setModel(modelo1);
        jl_CompraE.setModel(modelo1);
        //
        JOptionPane.showMessageDialog(null, "El Equipo Se Agrego con Exito");
        //
        tf_nombreE.setText("");
        tf_presupuesto.setText("");
        tf_copas.setText("");
        tf_estadio.setText("");
    }//GEN-LAST:event_bt_AgregarEquipoMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if (jl_Jugadores.getSelectedIndex()>=0) {
            jd_ModificarJugador.pack();
            jd_ModificarJugador.setModal(true);
            jd_ModificarJugador.setVisible(true);
            jd_ModificarJugador.setLocationRelativeTo(null);
            //
            
        }else{
            JOptionPane.showMessageDialog(null, "No selecciono nada de la lista");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        reload();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        jugador_seleccionado=(Jugador)jl_Jugadores.getSelectedValue();
        jugador_seleccionado.setNombre(tf_nombreJ1.getText());
        jugador_seleccionado.setPrecio(Integer.parseInt(tf_precio1.getText()));
        jugador_seleccionado.setPosicion(cb_pos1.getSelectedItem().toString());
        jugador_seleccionado.setHabilidad(tf_habilidad1.getText());
        jugador_seleccionado.setTecnica(tf_tecnica1.getText());
        jugador_seleccionado.setResistencia(tf_resistencia1.getText());
        DefaultListModel model = (DefaultListModel)jl_Jugadores.getModel();
        DefaultListModel model2=(DefaultListModel)jl_CompraJ.getModel();
        model.remove(jl_Jugadores.getSelectedIndex());
        model2.remove(jl_Jugadores.getSelectedIndex());
        model.addElement(jugador_seleccionado);
        model2.addElement(jugador_seleccionado);
        //
        tf_nombreJ1.setText("");
        tf_precio1.setText("");
        cb_pos1.setSelectedIndex(0);
        tf_habilidad1.setText("");
        tf_tecnica1.setText("");
        tf_resistencia1.setText("");
        jd_ModificarJugador.dispose();
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        if (jl_equipos.getSelectedIndex()>=0) {
            jd_ModificarEquipo.pack();
            jd_ModificarEquipo.setModal(true);
            jd_ModificarEquipo.setVisible(true);
            jd_ModificarEquipo.setLocationRelativeTo(null);
        }else{
            JOptionPane.showMessageDialog(null, "No selecciono nada de la lista");
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        reloadEquipo();
    }//GEN-LAST:event_jButton7MouseClicked

    private void bt_modEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_modEquiposMouseClicked
        equipo_seleccionado=(Equipo)jl_equipos.getSelectedValue();
        equipo_seleccionado.setNombre(tf_nombreE1.getText());
        equipo_seleccionado.setPresupuesto(Integer.parseInt(tf_presupuesto1.getText()));
        equipo_seleccionado.setCopas(Integer.parseInt(tf_copas1.getText()));
        equipo_seleccionado.setEstadio(tf_estadio1.getText());
        //
        DefaultListModel model = (DefaultListModel)jl_equipos.getModel();
        DefaultListModel modelo2 = (DefaultListModel)jl_CompraE.getModel();
        model.remove(jl_equipos.getSelectedIndex());
        modelo2.remove(jl_equipos.getSelectedIndex());
        model.addElement(equipo_seleccionado);
        modelo2.addElement(equipo_seleccionado);
        //
        jd_ModificarEquipo.dispose();
    }//GEN-LAST:event_bt_modEquiposMouseClicked

    private void bt_jugadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_jugadoresMouseClicked
        if (jl_Jugadores.getSelectedIndex()>=0) {
            DefaultListModel modelo = (DefaultListModel)jl_Jugadores.getModel();
            DefaultListModel modelo2 = (DefaultListModel)jl_CompraJ.getModel();
            modelo.remove(jl_Jugadores.getSelectedIndex());
            modelo2.remove(jl_Jugadores.getSelectedIndex());
            jl_Jugadores.setModel(modelo);
            jl_CompraJ.setModel(modelo2);
            
        }else{
            JOptionPane.showMessageDialog(null, "No tiene nada selecionado");
        }
    }//GEN-LAST:event_bt_jugadoresMouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        if (jl_equipos.getSelectedIndex()>=0) {
            DefaultListModel modelo = (DefaultListModel)jl_equipos.getModel();
            DefaultListModel modelo2 = (DefaultListModel)jl_CompraE.getModel();
            modelo.remove(jl_equipos.getSelectedIndex());
            modelo2.remove(jl_equipos.getSelectedIndex());
            jl_equipos.setModel(modelo);
            jl_CompraE.setModel(modelo2);
            
        }else{
            JOptionPane.showMessageDialog(null, "No tiene nada selecionado");
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jl_JugadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_JugadoresMouseClicked
        
    }//GEN-LAST:event_jl_JugadoresMouseClicked

    private void pp_propiedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pp_propiedadesActionPerformed
        
    }//GEN-LAST:event_pp_propiedadesActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        jd_ComprarJugador.pack();
        jd_ComprarJugador.setModal(true);
        jd_ComprarJugador.setVisible(true);
        jd_ComprarJugador.setLocationRelativeTo(null);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        jugador_seleccionado=(Jugador)jl_CompraJ.getSelectedValue();
        equipo_seleccionado = (Equipo) jl_CompraE.getSelectedValue();
        if (jl_CompraE.getSelectedIndex()>=0 && jl_CompraJ.getSelectedIndex()>=0) {
            
            int total;
            total=equipo_seleccionado.getPresupuesto()-jugador_seleccionado.getPrecio();
            equipo_seleccionado.setPresupuesto(total);
            if (total>=0) {
                equipo_seleccionado.getJugadores().add(jugador_seleccionado);
            }else{
                JOptionPane.showMessageDialog(null, "No le ajusta el money papu");
            }
        }
    }//GEN-LAST:event_jButton2MouseClicked

    public void reload(){
            jugador_seleccionado=(Jugador)jl_Jugadores.getSelectedValue();
            tf_nombreJ1.setText(jugador_seleccionado.getNombre());
            tf_precio1.setText(Integer.toString(jugador_seleccionado.getPrecio()));
            cb_pos1.setSelectedItem(jugador_seleccionado.getPosicion());
            tf_habilidad1.setText(jugador_seleccionado.getHabilidad());
            tf_tecnica1.setText(jugador_seleccionado.getTecnica());
            tf_resistencia1.setText(jugador_seleccionado.getResistencia());
    }
    public void reloadEquipo(){
            equipo_seleccionado = (Equipo) jl_equipos.getSelectedValue();
                tf_nombreE1.setText(equipo_seleccionado.getNombre());
                tf_presupuesto1.setText(Integer.toString(equipo_seleccionado.getPresupuesto()));
                tf_copas1.setText(Integer.toString(equipo_seleccionado.getCopas()));
                tf_estadio1.setText(equipo_seleccionado.getEstadio());
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_AgregarEquipo;
    private javax.swing.JButton bt_AgregarJugadores;
    private javax.swing.JButton bt_jugadores;
    private javax.swing.JButton bt_modEquipos;
    private javax.swing.JComboBox<String> cb_pos;
    private javax.swing.JComboBox<String> cb_pos1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JDialog jd_AgregarEquipo;
    private javax.swing.JDialog jd_AgregarJugador;
    private javax.swing.JDialog jd_ComprarJugador;
    private javax.swing.JDialog jd_ListarEquipos;
    private javax.swing.JDialog jd_ListarJugadores;
    private javax.swing.JDialog jd_ListarLiga;
    private javax.swing.JDialog jd_ModificarEquipo;
    private javax.swing.JDialog jd_ModificarJugador;
    private javax.swing.JList<Equipo> jl_CompraE;
    private javax.swing.JList<Jugador> jl_CompraJ;
    private javax.swing.JList<Jugador> jl_Jugadores;
    private javax.swing.JList<Equipo> jl_equipos;
    private javax.swing.JPopupMenu pop_jugadores;
    private javax.swing.JMenuItem pp_SacarJugador;
    private javax.swing.JMenuItem pp_propiedades;
    private javax.swing.JTextField tf_copas;
    private javax.swing.JTextField tf_copas1;
    private javax.swing.JTextField tf_estadio;
    private javax.swing.JTextField tf_estadio1;
    private javax.swing.JTextField tf_habilidad;
    private javax.swing.JTextField tf_habilidad1;
    private javax.swing.JTextField tf_nombreE;
    private javax.swing.JTextField tf_nombreE1;
    private javax.swing.JTextField tf_nombreJ;
    private javax.swing.JTextField tf_nombreJ1;
    private javax.swing.JTextField tf_precio;
    private javax.swing.JTextField tf_precio1;
    private javax.swing.JTextField tf_presupuesto;
    private javax.swing.JTextField tf_presupuesto1;
    private javax.swing.JTextField tf_resistencia;
    private javax.swing.JTextField tf_resistencia1;
    private javax.swing.JTextField tf_tecnica;
    private javax.swing.JTextField tf_tecnica1;
    // End of variables declaration//GEN-END:variables
    ArrayList<Jugador>jugadores = new ArrayList();
    ArrayList<Equipo>equipos = new ArrayList();
    Jugador jugador_seleccionado;
    Equipo equipo_seleccionado;
    DefaultMutableTreeNode nodo_seleccionado;
}
